### PR TITLE
Open source

### PR DESCRIPTION
**Pull request by OmarBitar**
by approving this pull request, then that means every MSU student who contributed to this project gives consent and approves of the GPL3 license. please reply with I consent if you approve of the license

### CODE REVIEW

**Comment by nweicker** [comment]
I approve of the license.

**Review by nweicker — APPROVED** [review]
I approve of the license.

**Review by vlazosar — APPROVED** [review]
I approve of the license.

**Review by justinandrewwu — APPROVED** [review]
I approve of the license

**Comment by matthewsawaged1** [comment]
I approve of the license

**Review by matthewsawaged1 — APPROVED** [review]

**Comment by OmarBitar** [comment]
I approve of the license

**Comment by OmarBitar** [comment]
accidentally closed pull request

**Pull request merged**
